services:
  - type: web
    name: compliance-auditor-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: sh start_backend.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openai
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: EMBEDDING_PROVIDER
        value: openai
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: CHUNK_SIZE
        value: "1000"
      - key: CHUNK_OVERLAP
        value: "150"
      - key: TOP_K
        value: "5"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: compliance-rules
      - key: DATA_DIR
        value: data

  - type: web
    name: compliance-auditor-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: streamlit run ui.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: compliance-auditor-backend
          property: host
